---create database customer_behaviour_Analysis

select * from customer

----Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) revenue from customer group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer where discount_applied ='yes' and purchase_amount >=
(select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5  item_purchased, round(avg(review_rating),2) avg_rating from customer group by item_purchased order by avg_rating desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select * from customer

select shipping_type, avg(purchase_amount) from customer where Shipping_Type in('Standard', 'Express') group by Shipping_Type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.


select subscription_status,count(customer_id) total_count, avg(purchase_amount) avg_amount, sum(purchase_amount) tot_amount from customer
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,sum(100 * case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate 
from customer group by item_purchased order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select * from customer

with customer_type as
(

select customer_id, Previous_Purchases, 
case when Previous_Purchases =1 then 'new'
     when Previous_Purchases between 2 and 10 then 'retuning' else 'loyal' end as customer_segment from customer)


select  customer_segment, count(*) as no_of_purchase from customer_type group by customer_segment


--Q8. What are the top 3 most purchased products within each category? 

select * from customer

select category,item_purchased, total_orders,item_rank from
(select category,item_purchased,count(customer_id) total_orders, row_number() over(partition by category order by count(customer_id) desc) 
item_rank from customer group by category,item_purchased) item_rank
where item_rank <=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customer

select Subscription_Status,count(customer_id) as repeat_bias from customer where Previous_Purchases <=5
group by Subscription_Status 

--Q10. What is the revenue contribution of each age group? 

select * from customer
select age_group,sum(purchase_amount) amount from customer group by age_group order by amount desc 


